# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      REPORTING_RERUN_CONDITION: "<< pipeline.parameters.reporting-run-context >>"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - run: gradle dependencies
      - run: gradle dependencies
      - run: gradle dependencies
      - run: gradle dependencies
      - run: gradle dependencies
      - run: gradle dependencies
      - run: gradle dependencies
      - run: gradle dependencies
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
            - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
            - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle dependencies
      - run: gradle dependencies
      - run: gradle dependencies
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test
  oop:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: gradle clean
      - run: gradle test

workflows:
  hithere:
    jobs:
      - build
      - oop
      - build
      - build
      - build
      - build
      - build
      - build
      - build
      - build
      - build
      - build
      - build
      - build
parameters:
  reporting-run-context:
    default: ""
    type: string